<?php
/**
 * Created by PhpStorm.
 * User: bigsave
 * Date: 2018/5/18
 * Time: 16:55
 */

namespace app\admin\model;


use think\Model;

class User extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }



}