<?php
/**
 * Created by PhpStorm.
 * User: bigsave
 * Date: 2017/10/20
 * Time: 10:57
 */
namespace app\admin\controller;

use think\Db;
use app\common\controller\CommonController;
use app\admin\model\NameList;

class Index extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $msg = array(
            'name'=>'name1',
        );
        $data = Db::name('list')
            ->select();
        return $this->fetch('index',$data);
    }

    public function lists(){
        $NameList = model('NameList');
        $NameList->name = 'thinkPhp5';
        $NameList->save();
        dump($NameList);die;
    }

    public function exportExcel(){
        //引用文件
        vendor('phpoffice.phpexcel.Classes.PHPExcel');
        $objPHPExcel = new \PHPExcel();

        $objPHPExcel->getProperties()->setCreator("Maarten Balliauw")
            ->setLastModifiedBy("Maarten Balliauw")
            ->setTitle("Office 2007 XLSX Test Document")
            ->setSubject("Office 2007 XLSX Test Document")
            ->setDescription("Test document for Office 2007 XLSX, generated using PHP classes.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("Test result file");


// Add some data
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A1', 'Hello')
            ->setCellValue('B2', 'world!')
            ->setCellValue('C1', 'Hello')
            ->setCellValue('D2', 'world!');

// Miscellaneous glyphs, UTF-8
        $objPHPExcel->setActiveSheetIndex(0)
            ->setCellValue('A4', 'Miscellaneous glyphs')
            ->setCellValue('A5', 'éàèùâêîôûëïüÿäöüç');

// Rename worksheet
        $objPHPExcel->getActiveSheet()->setTitle('Simple');


// Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $objPHPExcel->setActiveSheetIndex(0);


// Redirect output to a client’s web browser (Excel5)
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="01simple.xls"');
        header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
        header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
        header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
        header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
        header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
        header ('Pragma: public'); // HTTP/1.0

        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        exit('123321');
    }


    public function insertData(){

        $start = strtotime("2017-08-01");
        $end = strtotime("2017-09-01");
        for($i=$start;$i<=$end;$i+=86400){
            reportRegister($i);
        }
        exit("122");

    }

    public function test(){
        $array = [strtotime('2017-09-19'),strtotime('2017-08-25'),strtotime('2017-08-26'),strtotime('2017-08-27'),
            strtotime('2017-08-28'),strtotime('2017-08-29'),strtotime('2017-08-30'),strtotime('2017-06-16'),strtotime('2017-06-17')];
        foreach($array as $val){
            reportChannel($val);
        }
        exit();
    }
}
