<?php
/**
 * Created by PhpStorm.
 * User: lmx
 * Date: 2018/5/5
 * Time: 16:03
 */

namespace app\admin\controller;

use app\common\controller\CommonController;

class Login extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        dump($_POST);die;
    }

    /**
     * 后台登录页面
     */
    public function login(){

        return $this->fetch();
    }

    /**
     * 登录验证
     */
    public function doLogin(){
        $username = input('username');
        $password = input('password');
        if(empty($username) || empty($password)) $this->error('用户名或者密码不能为空',Url('/admin/login/login'));

        $user = db('user')->where(['username'=>$username])->find();
        if(!$user) $this->error('该用户不存在！',Url('/admin/login/login'));
        if($user['password'] != md5($password)) $this->error('密码错误',Url('/admin/login/login'));
        session('username',$username);
        $this->success('登录成功',Url('/admin/index/index'));

    }

    public function test(){

        return $this->fetch();
    }
}