<?php
/**
 * Created by PhpStorm.
 * User: lmx
 * Date: 2018/5/5
 * Time: 16:03
 */

namespace app\admin\controller;

use app\common\controller\CommonController;

class Login extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        dump($_POST);die;
    }

    /**
     * 后台登录页面
     */
    public function login(){

        return $this->fetch();
    }

    /**
     * 登录验证
     */
    public function doLogin(){
        dump($_POST);die;
    }

}