<?php
/**
 * Created by PhpStorm.
 * User: bigsave
 * Date: 2018/6/12
 * Time: 14:52
 */

namespace app\home\controller;


use think\Controller;

class Testserver extends controller
{


    private $public_key='MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC8aPwqWTVdLrzNcNZq1Cgf+h1nTcdfYRRQdZWXZiQf6uPGu6pFWu2LCgaldllt3oZlGfJucYavatnt/JqdhZtCkXQngs/qnnZt9xLmPD+rP0SGJxV5JjzVebR7GFW/FPmRfMDp9U6zb6Sz/H2cVPyuAaYDMGjajSqnPl6C8J4xuQIDAQAB';
    private $private_key='MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALxo/CpZNV0uvM1w1mrUKB/6HWdNx19hFFB1lZdmJB/q48a7qkVa7YsKBqV2WW3ehmUZ8m5xhq9q2e38mp2Fm0KRdCeCz+qedm33EuY8P6s/RIYnFXkmPNV5tHsYVb8U+ZF8wOn1TrNvpLP8fZxU/K4BpgMwaNqNKqc+XoLwnjG5AgMBAAECgYAigQ99Ke0t7XtCHGIIGmZmxMVRv9q9SugPfBkzKs9+0ON557BdFzPdfK6O6seh6VivdzsAouXJhkX24YXnRyqRizTWsBUc5ytTyh9biFir4bIo5fAp8WQENElg0LnnKmY7q7/MUzVAzv6gUHefg7VtFz8M0yMElsAmqywZ6TYtSQJBAPpHjFhI3rXBDcRjoN/i52oHmNlWPMyFrzXv84cx2bub5aD5lEStKokAlG4yAquPSxBNmBS5+/8qEwKmlPYfi7sCQQDAt2wtpVs/8T/UxDlhOKChiKKP46tnHIRoa9EcHBdsyfCVW+qXz+fFQC/JKrXJ6e9y8S5FiRQuxTWWDhQsZ48bAkEAuO4vJHjLnw8EBi37jBLUHYN5jHXtPM429arUjfvmv3plBToFNW2itVKpWnc3g97Af05mZkI6koNbQqUmAmqyywJAeg9y6BJUklJV8If8I9S/ALDO7b3woRVR0+V+A4TTXWcmByO5mT/od2mpGov/qgyOScnyWb5x1xG3V/xA0MMiwwJATNZYQXRSTTjvCvGRAy/neI6TJ6d8S26L8Y8qaAmwv82M933SDtgbb7ncj7JpIxc8r1+4UAkKcWOLaU+lLhFh0Q==';

    private $aesKey      = '5hod8TsThKtkx1LH';
    private $aesIV       = 'qvuXixMQ33m0rko2';
    private $url = 'http://php.xjlc.com/home/server/server';

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $paramDetail = [
            "requestNo"=>"xxxxxsxxxsss",
            "username"=>"eeeqqq",
            "timestamp"=>"123456"
        ];

        $data = [
            "interName"=>"TEST",
            "platform"=>'lmx',
            "detailData"=>$paramDetail,
            "sign"=>"fffffffffff",
            "timestamp"=>time(),
        ];
        $sign = \think\Loader::model('admin/SignService','service');
        $param = [];
        $param['param'] = $sign->param_aes_encode(json_encode($data),$this->private_key,$this->aesKey);
        $param['sign'] = $sign->private_encrypt($param['param'],$this->private_key);
        dump($param);die;
        $ret = $this->httpRequest($param);
        dump($ret);

    }

    private function httpRequest($param){

        $ch = curl_init();
        curl_setopt($ch,CURLOPT_URL,$this->url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $param);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $res = curl_exec($ch);
        curl_close($ch);
        return $res;
    }


}