<?php
/**
 * Created by PhpStorm.
 * User: bigsave
 * Date: 2018/6/12
 * Time: 14:52
 */

namespace app\home\controller;


use think\Controller;

class Testserver extends controller
{


    public  $private_key               = 'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0xCuegDXWM1FUj5s/hFif5Ca0XvVvo1W3b7XnM9TdEi1c3C0kSwrQp15fmVRoogsQ0LD0i/hbkgNhXZOgUqnu0hLZhvJl2O8HqFNeaVMQ0bccZ7BkaT594yvetgjyfn/u7YouKxR+GhrQVdN0FEGPHNH1jjSQgX+vfMe0ykibo4lOenEfx4uyTBcbQBVlvBzoVKw4gbxkQgTDdM3dwSaYS3CXmQB5QCs3VWXRhPCj/pJWolg3gJsdzkGrsmOQiA0VlOfyRJcmKLSEhRcLpdsNI44Az/hGoPZmvbWILJ7WJS4cddQTC9/NEOV6qO7h8a9/lfB5rpQmO7F4s7WPK9AFAgMBAAECggEAKpCm1MPL6Yxb8lV+cQ5w7/WBR6e0k30aif88Dh0eWpAVLnCKEKm6+jbu+gPY5GqDwInjoTH0YVuYgCzQvke4zAubdK1aFrFmV59DQk/6x1Makw23c2100Z/UjLTAlplC9rfoecabJLZw6e3LxOGgLlrS9cduiTh1IJV5URDw1/Tc6Nvvppza04ewM+ie8YJ04iSeh4lsTGcT4pfKqzZ0+z3EfK/waXNXG1O8phVKKi3Vn3GsGHT5JKcWSOWaDv/6Dylc3MgtWK3YDCjOBypxmWJkiadijQJWUI00QqVprdg2xnPBmfFeeTj02FOFXzTamqaw0lDuKnNAKqDBcGPNYQKBgQDXSjp/GLcxmQXJcHcvvyN+Z8itJtRuxvFz6KsW1A0Mp0gfQqMKrDo6X9DYrDoIvizMm9p7tC4YYnftjmfwFdFH6ZchrslOPOvzC1OalicTb93clfM4SGMjoGMuiZWadLJUIgIywFw76IM53g/32VbL8gYsK0GyWoSEmqgiRRDQDwKBgQDW8rfGdL3IHCcN5/NzN+RKjWUZzsqRmUcBf6/huJkoYPnEWhAnA4FaXpIWmrW7+qe0yafzs76C1mgQKqFT81CQoeoy/CHNV7udm68gn46PSAFhl0FodqmHnMGyZL/0AM2umpeYEkWY1bL+iPM/LuvyBtaTt6LjMxL30WwfJevKqwKBgQCINo3GRmP5/IB90CuIyR1y58U/UJcNs8+m72n4WpgbDmgCZ03y/b8lmePwgx+A0ppTprRYmkqj4QFSC0zVyWgNYMzfYdA6MS90KhFueFwm3xt3amRlkt8u9lZqZmCCRh1iP9Y2OCDjQpxsa4Sc4yUYinu/TGsXpk+7+oIwlJQrnwKBgDjLAMuq5MoOxjLiamyzA9q+6UucW+GEgkJfHnWhdLY6iUPcGBB22KKsAiV+0y3L2Kvn7Dxz7Y5cYDqFSQMJcuwEHAFEpRnAaI4IKImSHvS0rci/UkTrtXdjb7pW7HDoFXBg4FUJ3uG29QhT3xF+sFDOhbuZ9avaPtTDvLGuL1LpAoGBAK+DfaiwQk2NlIEpej4aZDN/itNk6dMPxvHG/Msg4VvjlGAXsfYpzeqa4ytJcH60mBSf2VZXaDmdwX9EOdBRGNVBypEr7sOmnxllemPnXvA+pc3yIWulzxxxT6Qr2AlZxjyTngW5W/QkUE0CpbAP9HEg1EoiHDSdJMm8L5CzU24q';
    public  $public_key                = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtMQrnoA11jNRVI+bP4RYn+QmtF71b6NVt2+15zPU3RItXNwtJEsK0KdeX5lUaKILENCw9Iv4W5IDYV2ToFKp7tIS2YbyZdjvB6hTXmlTENG3HGewZGk+feMr3rYI8n5/7u2KLisUfhoa0FXTdBRBjxzR9Y40kIF/r3zHtMpIm6OJTnpxH8eLskwXG0AVZbwc6FSsOIG8ZEIEw3TN3cEmmEtwl5kAeUArN1Vl0YTwo/6SVqJYN4CbHc5Bq7JjkIgNFZTn8kSXJii0hIUXC6XbDSOOAM/4RqD2Zr21iCye1iUuHHXUEwvfzRDleqju4fGvf5Xwea6UJjuxeLO1jyvQBQIDAQAB';

    private $aesKey      = '5hod8TsThKtkx1LH';
    private $aesIV       = 'qvuXixMQ33m0rko2';
    private $url = 'http://php.xjlc.com/home/server/server';

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $paramDetail = [
            "requestNo"=>"xxxxxsxxxsss",
            "username"=>"eeeqqq",
            "timestamp"=>"123456"
        ];

        $data = [
            "interName"=>"TEST",
            "platform"=>'lmx',
            "detailData"=>$paramDetail,
            "timestamp"=>time(),
        ];
        $sign = \think\Loader::model('admin/SignService','service');
        $param = [];
        $param['param'] = $sign->param_aes_encode(json_encode($data),$this->aesKey,$this->aesIV);

        $param['sign'] = $sign->ecsSign($param['param'],$this->private_key);
        $ret = $this->httpRequest($param);
        $req = json_decode($ret,1);
//        dump($req);die;

        $verify = $sign->verify($req['param'],$req['sign'],$this->public_key);

        if(!$verify) exception('验签失败~！');

        $content = $sign->param_aes_decode($req['param'],$this->aesKey,$this->aesIV);

        dump(json_decode($content,1));

    }

    public function gate(){
        $data = [1,2,3,4];
        $ret = $this->gateRequest($this->url,'',$data,'');
        dump($ret);
    }

    private function httpRequest($param){

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,$this->url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $param);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $res = curl_exec($ch);
        curl_close($ch);
        return $res;
    }

    private function gateRequest($url, $headers, $data, $key) {
        //1为调试模式
        $debug = 0;
        $temp = $data;
        $Html = '
            <!DOCTYPE HTML>
            <html>
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
                <title>跳转中...</title>
            </head>
            <body>';
        $Html .= "<form id='SubmitPost' name='SubmitPost' action='" . $url . "' method='POST'>";
        foreach ($temp as $key => $val) {
            if ($debug) {
                $Html .= "$key:&nbsp;&nbsp;&nbsp;&nbsp;<input type='text'  name='" . $key . "' value='" . $val . "'  /><br>";
            } else {
                $Html .= "<input type='hidden'  name='" . $key . "' value='" . $val . "'  /><br>";
            }
        }
        $Html .= "<input type='submit' value='submit' ".($debug ? '' : 'hidden' ).">";
        $Html .= '
            </form>
            <script type="text/javascript">' .
            ($debug ? 'alert(document.getElementById("j_serviceName").name);
                document.forms["SubmitPost"].submit();' : 'document.forms["SubmitPost"].submit();')
            . '</script></body></html>';
        echo $Html;
    }



}